// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zcfdumlnwexqxtoiwbcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpjZmR1bWxud2V4cXh0b2l3YmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMDc2NzEsImV4cCI6MjA2MjU4MzY3MX0.OeVbm8pv1zH4zOIf23zPgyeu8iXemw4cddefjhupcvE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);